### ISSUE TITLE
Entering the wrong versions throws a redirect loop

### ISSUE THREAD

**Issue by jwoertink** [stephendolan/lucky_diff#344]
Take this URL for example: https://luckydiff.com?from=0.27.0&to=0.28.0

I was thinking the version numbers were taken from the CLI which would be 0.27.0 -> 0.28.0. Turns out it's based on the Lucky shard itself, so it should be 0.27.2.

Maybe it could try and find the closest version, or just redirect to a single 404 page?

**Comment by stephendolan** [comment]
Closed with https://github.com/stephendolan/lucky_diff/commit/c58e5d574979e7f9ea48bfed4586954975d683c9

We'll just redirect to the latest upgrade path on typos for now.
