### ISSUE TITLE
Allow minimizing files

### ISSUE THREAD

**Issue by matthewmcgarvey** [stephendolan/lucky_diff#502]
It'd be nice to be able to minimize the files that I am either ignoring or finished with to make it easier to scroll around

**Comment by stephendolan** [comment]
This looks possible by switching from using the raw diff to DiffHTMLUI:

https://github.com/rtfpessoa/diff2html

**Comment by stephendolan** [comment]
Couldn't get it figured out without adding a bunch of custom typing stuff to make TypeScript happy - opened https://github.com/rtfpessoa/diff2html/issues/422
